name = "backend"
main = "src/index.ts"
compatibility_date = "2023-01-01"
node_compat = true

[[d1_databases]]
binding = "DB"
database_name = "shop"
database_id = "2f334e93-d1ac-4f14-b0cb-68d45d48916f"

[[r2_buckets]]
binding = "R2"
bucket_name = "shop-uploads"

[vars]
JWT_SECRET = "your-secret-key-here"

[build]
command = "npm run build" 