name = "backend"
main = "src/index.ts"
compatibility_date = "2023-01-01"
node_compat = true

[[d1_databases]]
binding = "DB"
database_name = "shop"
database_id = "your-database-id"

[[r2_buckets]]
binding = "R2"
bucket_name = "shop-uploads"

[vars]
JWT_SECRET = "your-jwt-secret"

[build]
command = "npm run build" 